const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: '123456',
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: '123456',
      role: 'user',
    },
  ],
  products: [
    {
      name: 'Castelejo Caverns',
      slug: 'castelejo-caverns',
      category: "Men's casual T-shirt",
      description: 'Classic Leisure style with modern comfort',
      images: [
        '/castelejo-mens-white-flat-back.webp',
        '/castelejo-mens-white-flat-front.webp',
      ],
      price: 49.99,
      brand: 'Wipeout.Surf',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        '/castelejo-mens-white-flat-back.webp',
        '/castelejo-mens-white-flat-front.webp',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        '/castelejo-mens-white-flat-back.webp',
        '/castelejo-mens-white-flat-front.webp',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/castelejo-mens-white-flat-back.webp',
        '/castelejo-mens-white-flat-front.webp',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        '/castelejo-mens-white-flat-back.webp',
        '/castelejo-mens-white-flat-front.webp',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/castelejo-mens-white-flat-back.webp',
        '/castelejo-mens-white-flat-front.webp',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
